### PR TITLE
Added support to add a separate SSLSocketFactory for a Client

### PR DESCRIPTION
**Pull request by KwintenP**
- Added a new implementation of the TransportFactory. This returns
instances of the Transport class with support for SSL.
- Added a new constructor to the Client class that accepts an instance
of the SSLSocketFactory as extra parameter. During construction of the
Client, the correct TransportFactory implementation is created using
the TransportFactoryFactory.
- Added a TransportFactoryFactory that creates the correct
TransportFactory.

### CODE REVIEW

**Comment by seize-the-dave** [comment]
I don't agree that the `Client` constructor shouldn't take a `SSLSocketFactory`.  This is really what I had in mind:

```
Client client = ...
SSLSocketFactory sslSocketFactory = ...
TransportFactory transportFactory = new UrlConnectionTransportFactory(sslSocketFactory);
client.setTransportFactory(transportFactory);
```

I think a custom socket factory is useful enough to add to the `UrlConnectionTransportFactory` as an optional constructor.  It would then follow that each `Transport` could then take an optional `SSLSocketFactory` too, and configure connections with it if non-null.

**Comment by KwintenP** [comment]
Implemented as described.

**Comment by seize-the-dave** [comment]
The `sslSocketFactory` should be a field in `UrlConnectionGetTransport` and `UrlConnectionPostTransport`, not in `AbstractTransport`.  Other than that, it looks great!

**Comment by KwintenP** [comment]
Updated.

**Comment by seize-the-dave** [comment]
Thanks @KwintenP .  I should be able to get a release out this evening.

**Comment by KwintenP** [comment]
Great! Thanks for you cooperation!

**Pull request merged**
