### PR TITLE
Add support for more capabilities

### PR DESCRIPTION
**Pull request by ngaya-ll**
Support additional capabilities per https://www.ietf.org/id/draft-gutmann-scep-06.txt:
* `AES`
* `SCEPStandard`
* `Update`

### CODE REVIEW

**Comment by seize-the-dave** [comment]
@ngaya-ll have you tried using AES against a compatible server?

**Comment by ngaya-ll** [comment]
I updated one of the integration tests to use AES.  Let me know if you'd rather have that be a separate test.

**Comment by seize-the-dave** [comment]
I think a separate test would be more beneficial - thanks.

**Comment by ngaya-ll** [comment]
Added an encode/decode test instead.

**Pull request merged**
